// <auto-generated />
namespace IMSWEB.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DropRoleandOldUser : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropRoleandOldUser));
        
        string IMigrationMetadata.Id
        {
            get { return "201708180916285_Drop Role and Old User"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
