namespace IMSWEB.Data.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ChangeIdentityTablesPrimarykey : DbMigration
    {
        public override void Up()
        {
            //DropForeignKey("dbo.CashCollections", "CustomerID", "dbo.Customers");
            //DropForeignKey("dbo.SOrders", "CustomerID", "dbo.Customers");
            //DropForeignKey("dbo.CreditSales", "CustomerID", "dbo.Customers");
            //DropForeignKey("dbo.CreditSaleProducts", "CreditSalesID", "dbo.CreditSales");
            //DropForeignKey("dbo.CreditSalesDetails", "CreditSalesID", "dbo.CreditSales");
            //DropForeignKey("dbo.Products", "CategoryID", "dbo.Categorys");
            //DropForeignKey("dbo.CashCollections", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Categorys", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Companies", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.CreditSales", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Customers", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.DamageProducts", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Employees", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Expenditures", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Models", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.POrders", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Suppliers", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.SOrders", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Stocks", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.SystemInformations", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Users", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Products", "CompanyID", "dbo.Companies");
            //DropForeignKey("dbo.Customers", "EmployeeID", "dbo.Employees");
            //DropForeignKey("dbo.Employees", "DesignationID", "dbo.Designations");
            //DropForeignKey("dbo.Expenditures", "ExpenseItemID", "dbo.ExpenseItems");
            //DropForeignKey("dbo.Products", "ModelID", "dbo.Models");
            //DropForeignKey("dbo.POrderDetails", "POrderID", "dbo.POrders");
            //DropForeignKey("dbo.POProductDetails", "POrderDetailID", "dbo.POrderDetails");
            //DropForeignKey("dbo.CashCollections", "Supplier_SupplierID", "dbo.Suppliers");
            //DropForeignKey("dbo.POrders", "SupplierID", "dbo.Suppliers");
            //DropForeignKey("dbo.SOrderDetails", "SOrderID", "dbo.SOrders");
            //DropForeignKey("dbo.CreditSaleProducts", "StockDetail_SDetailID", "dbo.StockDetails");
            //DropForeignKey("dbo.SOrderDetails", "StockDetail_SDetailID", "dbo.StockDetails");
            //DropForeignKey("dbo.StockDetails", "StockID", "dbo.Stocks");
            //DropForeignKey("dbo.UserClaims", "UserId", "dbo.Users");
            //DropForeignKey("dbo.UserLogins", "UserId", "dbo.Users");
            //DropForeignKey("dbo.UserRoles", "UserId", "dbo.Users");
            //DropForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles");
            //DropIndex("dbo.UserClaims", new[] { "UserId" });
            //DropIndex("dbo.UserLogins", new[] { "UserId" });
            //DropIndex("dbo.UserRoles", new[] { "UserId" });
            //DropIndex("dbo.UserRoles", new[] { "RoleId" });
            //DropPrimaryKey("dbo.CashCollections");
            //DropPrimaryKey("dbo.Customers");
            //DropPrimaryKey("dbo.CreditSales");
            //DropPrimaryKey("dbo.CreditSaleProducts");
            //DropPrimaryKey("dbo.Categorys");
            //DropPrimaryKey("dbo.SisterConcerns");
            //DropPrimaryKey("dbo.Companies");
            //DropPrimaryKey("dbo.DamageProducts");
            //DropPrimaryKey("dbo.Employees");
            //DropPrimaryKey("dbo.Designations");
            //DropPrimaryKey("dbo.Expenditures");
            //DropPrimaryKey("dbo.ExpenseItems");
            //DropPrimaryKey("dbo.Models");
            //DropPrimaryKey("dbo.POrders");
            //DropPrimaryKey("dbo.POrderDetails");
            //DropPrimaryKey("dbo.POProductDetails");
            //DropPrimaryKey("dbo.Suppliers");
            //DropPrimaryKey("dbo.SOrders");
            //DropPrimaryKey("dbo.SOrderDetails");
            //DropPrimaryKey("dbo.StockDetails");
            //DropPrimaryKey("dbo.Stocks");
            //DropPrimaryKey("dbo.SystemInformations");
            //DropPrimaryKey("dbo.Users");
            //DropPrimaryKey("dbo.UserLogins");
            //DropPrimaryKey("dbo.UserRoles");
            //DropPrimaryKey("dbo.SaleOffers");
            //DropPrimaryKey("dbo.Errors");
            //DropPrimaryKey("dbo.Roles");
            //AlterColumn("dbo.CashCollections", "CashCollectionID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Customers", "CustomerID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.CreditSales", "CreditSalesID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.CreditSaleProducts", "CreditSaleProductsID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Categorys", "CategoryID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.SisterConcerns", "ConcernID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Companies", "CompanyID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.DamageProducts", "DamageProID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Employees", "EmployeeID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Designations", "DesignationID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Expenditures", "ExpenditureID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.ExpenseItems", "ExpenseItemID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Models", "ModelID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.POrders", "POrderID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.POrderDetails", "POrderDetailID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.POProductDetails", "POPDID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Suppliers", "SupplierID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.SOrders", "SOrderID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.SOrderDetails", "SOrderDetailID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.StockDetails", "SDetailID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Stocks", "StockID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.SystemInformations", "SystemInfoID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Users", "Id", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.UserClaims", "UserId", c => c.Int(nullable: false));
            //AlterColumn("dbo.UserLogins", "UserId", c => c.Int(nullable: false));
            //AlterColumn("dbo.UserRoles", "UserId", c => c.Int(nullable: false));
            //AlterColumn("dbo.UserRoles", "RoleId", c => c.Int(nullable: false));
            //AlterColumn("dbo.SaleOffers", "OfferID", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Errors", "Id", c => c.Int(nullable: false, identity: true));
            //AlterColumn("dbo.Errors", "Message", c => c.String(nullable: false, maxLength: 4000, unicode: false));
            //AlterColumn("dbo.Errors", "StackTrace", c => c.String(nullable: false, maxLength: 4000, unicode: false));
            //AlterColumn("dbo.Roles", "Id", c => c.Int(nullable: false, identity: true));
            //AddPrimaryKey("dbo.CashCollections", "CashCollectionID");
            //AddPrimaryKey("dbo.Customers", "CustomerID");
            //AddPrimaryKey("dbo.CreditSales", "CreditSalesID");
            //AddPrimaryKey("dbo.CreditSaleProducts", "CreditSaleProductsID");
            //AddPrimaryKey("dbo.Categorys", "CategoryID");
            //AddPrimaryKey("dbo.SisterConcerns", "ConcernID");
            //AddPrimaryKey("dbo.Companies", "CompanyID");
            //AddPrimaryKey("dbo.DamageProducts", "DamageProID");
            //AddPrimaryKey("dbo.Employees", "EmployeeID");
            //AddPrimaryKey("dbo.Designations", "DesignationID");
            //AddPrimaryKey("dbo.Expenditures", "ExpenditureID");
            //AddPrimaryKey("dbo.ExpenseItems", "ExpenseItemID");
            //AddPrimaryKey("dbo.Models", "ModelID");
            //AddPrimaryKey("dbo.POrders", "POrderID");
            //AddPrimaryKey("dbo.POrderDetails", "POrderDetailID");
            //AddPrimaryKey("dbo.POProductDetails", "POPDID");
            //AddPrimaryKey("dbo.Suppliers", "SupplierID");
            //AddPrimaryKey("dbo.SOrders", "SOrderID");
            //AddPrimaryKey("dbo.SOrderDetails", "SOrderDetailID");
            //AddPrimaryKey("dbo.StockDetails", "SDetailID");
            //AddPrimaryKey("dbo.Stocks", "StockID");
            //AddPrimaryKey("dbo.SystemInformations", "SystemInfoID");
            //AddPrimaryKey("dbo.Users", "Id");
            //AddPrimaryKey("dbo.UserLogins", new[] { "LoginProvider", "ProviderKey", "UserId" });
            //AddPrimaryKey("dbo.UserRoles", new[] { "UserId", "RoleId" });
            //AddPrimaryKey("dbo.SaleOffers", "OfferID");
            //AddPrimaryKey("dbo.Errors", "Id");
            //AddPrimaryKey("dbo.Roles", "Id");
            //CreateIndex("dbo.UserClaims", "UserId");
            //CreateIndex("dbo.UserLogins", "UserId");
            //CreateIndex("dbo.UserRoles", "UserId");
            //CreateIndex("dbo.UserRoles", "RoleId");
            //AddForeignKey("dbo.CashCollections", "CustomerID", "dbo.Customers", "CustomerID");
            //AddForeignKey("dbo.SOrders", "CustomerID", "dbo.Customers", "CustomerID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSales", "CustomerID", "dbo.Customers", "CustomerID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSaleProducts", "CreditSalesID", "dbo.CreditSales", "CreditSalesID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSalesDetails", "CreditSalesID", "dbo.CreditSales", "CreditSalesID", cascadeDelete: true);
            //AddForeignKey("dbo.Products", "CategoryID", "dbo.Categorys", "CategoryID", cascadeDelete: true);
            //AddForeignKey("dbo.CashCollections", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Categorys", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Companies", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSales", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Customers", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.DamageProducts", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Employees", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Expenditures", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Models", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.POrders", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Suppliers", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.SOrders", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Stocks", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.SystemInformations", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Users", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Products", "CompanyID", "dbo.Companies", "CompanyID", cascadeDelete: true);
            //AddForeignKey("dbo.Customers", "EmployeeID", "dbo.Employees", "EmployeeID", cascadeDelete: true);
            //AddForeignKey("dbo.Employees", "DesignationID", "dbo.Designations", "DesignationID", cascadeDelete: true);
            //AddForeignKey("dbo.Expenditures", "ExpenseItemID", "dbo.ExpenseItems", "ExpenseItemID", cascadeDelete: true);
            //AddForeignKey("dbo.Products", "ModelID", "dbo.Models", "ModelID", cascadeDelete: true);
            //AddForeignKey("dbo.POrderDetails", "POrderID", "dbo.POrders", "POrderID", cascadeDelete: true);
            //AddForeignKey("dbo.POProductDetails", "POrderDetailID", "dbo.POrderDetails", "POrderDetailID", cascadeDelete: true);
            //AddForeignKey("dbo.CashCollections", "Supplier_SupplierID", "dbo.Suppliers", "SupplierID");
            //AddForeignKey("dbo.POrders", "SupplierID", "dbo.Suppliers", "SupplierID", cascadeDelete: true);
            //AddForeignKey("dbo.SOrderDetails", "SOrderID", "dbo.SOrders", "SOrderID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSaleProducts", "StockDetail_SDetailID", "dbo.StockDetails", "SDetailID");
            //AddForeignKey("dbo.SOrderDetails", "StockDetail_SDetailID", "dbo.StockDetails", "SDetailID");
            //AddForeignKey("dbo.StockDetails", "StockID", "dbo.Stocks", "StockID", cascadeDelete: true);
            //AddForeignKey("dbo.UserClaims", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.UserLogins", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.UserRoles", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
        }
        
        public override void Down()
        {
            //DropForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles");
            //DropForeignKey("dbo.UserRoles", "UserId", "dbo.Users");
            //DropForeignKey("dbo.UserLogins", "UserId", "dbo.Users");
            //DropForeignKey("dbo.UserClaims", "UserId", "dbo.Users");
            //DropForeignKey("dbo.StockDetails", "StockID", "dbo.Stocks");
            //DropForeignKey("dbo.SOrderDetails", "StockDetail_SDetailID", "dbo.StockDetails");
            //DropForeignKey("dbo.CreditSaleProducts", "StockDetail_SDetailID", "dbo.StockDetails");
            //DropForeignKey("dbo.SOrderDetails", "SOrderID", "dbo.SOrders");
            //DropForeignKey("dbo.POrders", "SupplierID", "dbo.Suppliers");
            //DropForeignKey("dbo.CashCollections", "Supplier_SupplierID", "dbo.Suppliers");
            //DropForeignKey("dbo.POProductDetails", "POrderDetailID", "dbo.POrderDetails");
            //DropForeignKey("dbo.POrderDetails", "POrderID", "dbo.POrders");
            //DropForeignKey("dbo.Products", "ModelID", "dbo.Models");
            //DropForeignKey("dbo.Expenditures", "ExpenseItemID", "dbo.ExpenseItems");
            //DropForeignKey("dbo.Employees", "DesignationID", "dbo.Designations");
            //DropForeignKey("dbo.Customers", "EmployeeID", "dbo.Employees");
            //DropForeignKey("dbo.Products", "CompanyID", "dbo.Companies");
            //DropForeignKey("dbo.Users", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.SystemInformations", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Stocks", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.SOrders", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Suppliers", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.POrders", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Models", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Expenditures", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Employees", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.DamageProducts", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Customers", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.CreditSales", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Companies", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Categorys", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.CashCollections", "ConcernID", "dbo.SisterConcerns");
            //DropForeignKey("dbo.Products", "CategoryID", "dbo.Categorys");
            //DropForeignKey("dbo.CreditSalesDetails", "CreditSalesID", "dbo.CreditSales");
            //DropForeignKey("dbo.CreditSaleProducts", "CreditSalesID", "dbo.CreditSales");
            //DropForeignKey("dbo.CreditSales", "CustomerID", "dbo.Customers");
            //DropForeignKey("dbo.SOrders", "CustomerID", "dbo.Customers");
            //DropForeignKey("dbo.CashCollections", "CustomerID", "dbo.Customers");
            //DropIndex("dbo.UserRoles", new[] { "RoleId" });
            //DropIndex("dbo.UserRoles", new[] { "UserId" });
            //DropIndex("dbo.UserLogins", new[] { "UserId" });
            //DropIndex("dbo.UserClaims", new[] { "UserId" });
            //DropPrimaryKey("dbo.Roles");
            //DropPrimaryKey("dbo.Errors");
            //DropPrimaryKey("dbo.SaleOffers");
            //DropPrimaryKey("dbo.UserRoles");
            //DropPrimaryKey("dbo.UserLogins");
            //DropPrimaryKey("dbo.Users");
            //DropPrimaryKey("dbo.SystemInformations");
            //DropPrimaryKey("dbo.Stocks");
            //DropPrimaryKey("dbo.StockDetails");
            //DropPrimaryKey("dbo.SOrderDetails");
            //DropPrimaryKey("dbo.SOrders");
            //DropPrimaryKey("dbo.Suppliers");
            //DropPrimaryKey("dbo.POProductDetails");
            //DropPrimaryKey("dbo.POrderDetails");
            //DropPrimaryKey("dbo.POrders");
            //DropPrimaryKey("dbo.Models");
            //DropPrimaryKey("dbo.ExpenseItems");
            //DropPrimaryKey("dbo.Expenditures");
            //DropPrimaryKey("dbo.Designations");
            //DropPrimaryKey("dbo.Employees");
            //DropPrimaryKey("dbo.DamageProducts");
            //DropPrimaryKey("dbo.Companies");
            //DropPrimaryKey("dbo.SisterConcerns");
            //DropPrimaryKey("dbo.Categorys");
            //DropPrimaryKey("dbo.CreditSaleProducts");
            //DropPrimaryKey("dbo.CreditSales");
            //DropPrimaryKey("dbo.Customers");
            //DropPrimaryKey("dbo.CashCollections");
            //AlterColumn("dbo.Roles", "Id", c => c.String(nullable: false, maxLength: 128));
            //AlterColumn("dbo.Errors", "StackTrace", c => c.String(nullable: false, maxLength: 1500, unicode: false));
            //AlterColumn("dbo.Errors", "Message", c => c.String(nullable: false, maxLength: 1500, unicode: false));
            //AlterColumn("dbo.Errors", "Id", c => c.Int(nullable: false));
            //AlterColumn("dbo.SaleOffers", "OfferID", c => c.Int(nullable: false));
            //AlterColumn("dbo.UserRoles", "RoleId", c => c.String(nullable: false, maxLength: 128));
            //AlterColumn("dbo.UserRoles", "UserId", c => c.String(nullable: false, maxLength: 128));
            //AlterColumn("dbo.UserLogins", "UserId", c => c.String(nullable: false, maxLength: 128));
            //AlterColumn("dbo.UserClaims", "UserId", c => c.String(nullable: false, maxLength: 128));
            //AlterColumn("dbo.Users", "Id", c => c.String(nullable: false, maxLength: 128));
            //AlterColumn("dbo.SystemInformations", "SystemInfoID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Stocks", "StockID", c => c.Int(nullable: false));
            //AlterColumn("dbo.StockDetails", "SDetailID", c => c.Int(nullable: false));
            //AlterColumn("dbo.SOrderDetails", "SOrderDetailID", c => c.Int(nullable: false));
            //AlterColumn("dbo.SOrders", "SOrderID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Suppliers", "SupplierID", c => c.Int(nullable: false));
            //AlterColumn("dbo.POProductDetails", "POPDID", c => c.Int(nullable: false));
            //AlterColumn("dbo.POrderDetails", "POrderDetailID", c => c.Int(nullable: false));
            //AlterColumn("dbo.POrders", "POrderID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Models", "ModelID", c => c.Int(nullable: false));
            //AlterColumn("dbo.ExpenseItems", "ExpenseItemID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Expenditures", "ExpenditureID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Designations", "DesignationID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Employees", "EmployeeID", c => c.Int(nullable: false));
            //AlterColumn("dbo.DamageProducts", "DamageProID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Companies", "CompanyID", c => c.Int(nullable: false));
            //AlterColumn("dbo.SisterConcerns", "ConcernID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Categorys", "CategoryID", c => c.Int(nullable: false));
            //AlterColumn("dbo.CreditSaleProducts", "CreditSaleProductsID", c => c.Int(nullable: false));
            //AlterColumn("dbo.CreditSales", "CreditSalesID", c => c.Int(nullable: false));
            //AlterColumn("dbo.Customers", "CustomerID", c => c.Int(nullable: false));
            //AlterColumn("dbo.CashCollections", "CashCollectionID", c => c.Int(nullable: false));
            //AddPrimaryKey("dbo.Roles", "Id");
            //AddPrimaryKey("dbo.Errors", "Id");
            //AddPrimaryKey("dbo.SaleOffers", "OfferID");
            //AddPrimaryKey("dbo.UserRoles", new[] { "UserId", "RoleId" });
            //AddPrimaryKey("dbo.UserLogins", new[] { "LoginProvider", "ProviderKey", "UserId" });
            //AddPrimaryKey("dbo.Users", "Id");
            //AddPrimaryKey("dbo.SystemInformations", "SystemInfoID");
            //AddPrimaryKey("dbo.Stocks", "StockID");
            //AddPrimaryKey("dbo.StockDetails", "SDetailID");
            //AddPrimaryKey("dbo.SOrderDetails", "SOrderDetailID");
            //AddPrimaryKey("dbo.SOrders", "SOrderID");
            //AddPrimaryKey("dbo.Suppliers", "SupplierID");
            //AddPrimaryKey("dbo.POProductDetails", "POPDID");
            //AddPrimaryKey("dbo.POrderDetails", "POrderDetailID");
            //AddPrimaryKey("dbo.POrders", "POrderID");
            //AddPrimaryKey("dbo.Models", "ModelID");
            //AddPrimaryKey("dbo.ExpenseItems", "ExpenseItemID");
            //AddPrimaryKey("dbo.Expenditures", "ExpenditureID");
            //AddPrimaryKey("dbo.Designations", "DesignationID");
            //AddPrimaryKey("dbo.Employees", "EmployeeID");
            //AddPrimaryKey("dbo.DamageProducts", "DamageProID");
            //AddPrimaryKey("dbo.Companies", "CompanyID");
            //AddPrimaryKey("dbo.SisterConcerns", "ConcernID");
            //AddPrimaryKey("dbo.Categorys", "CategoryID");
            //AddPrimaryKey("dbo.CreditSaleProducts", "CreditSaleProductsID");
            //AddPrimaryKey("dbo.CreditSales", "CreditSalesID");
            //AddPrimaryKey("dbo.Customers", "CustomerID");
            //AddPrimaryKey("dbo.CashCollections", "CashCollectionID");
            //CreateIndex("dbo.UserRoles", "RoleId");
            //CreateIndex("dbo.UserRoles", "UserId");
            //CreateIndex("dbo.UserLogins", "UserId");
            //CreateIndex("dbo.UserClaims", "UserId");
            //AddForeignKey("dbo.UserRoles", "RoleId", "dbo.Roles", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.UserRoles", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.UserLogins", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.UserClaims", "UserId", "dbo.Users", "Id", cascadeDelete: true);
            //AddForeignKey("dbo.StockDetails", "StockID", "dbo.Stocks", "StockID", cascadeDelete: true);
            //AddForeignKey("dbo.SOrderDetails", "StockDetail_SDetailID", "dbo.StockDetails", "SDetailID");
            //AddForeignKey("dbo.CreditSaleProducts", "StockDetail_SDetailID", "dbo.StockDetails", "SDetailID");
            //AddForeignKey("dbo.SOrderDetails", "SOrderID", "dbo.SOrders", "SOrderID", cascadeDelete: true);
            //AddForeignKey("dbo.POrders", "SupplierID", "dbo.Suppliers", "SupplierID", cascadeDelete: true);
            //AddForeignKey("dbo.CashCollections", "Supplier_SupplierID", "dbo.Suppliers", "SupplierID");
            //AddForeignKey("dbo.POProductDetails", "POrderDetailID", "dbo.POrderDetails", "POrderDetailID", cascadeDelete: true);
            //AddForeignKey("dbo.POrderDetails", "POrderID", "dbo.POrders", "POrderID", cascadeDelete: true);
            //AddForeignKey("dbo.Products", "ModelID", "dbo.Models", "ModelID", cascadeDelete: true);
            //AddForeignKey("dbo.Expenditures", "ExpenseItemID", "dbo.ExpenseItems", "ExpenseItemID", cascadeDelete: true);
            //AddForeignKey("dbo.Employees", "DesignationID", "dbo.Designations", "DesignationID", cascadeDelete: true);
            //AddForeignKey("dbo.Customers", "EmployeeID", "dbo.Employees", "EmployeeID", cascadeDelete: true);
            //AddForeignKey("dbo.Products", "CompanyID", "dbo.Companies", "CompanyID", cascadeDelete: true);
            //AddForeignKey("dbo.Users", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.SystemInformations", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Stocks", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.SOrders", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Suppliers", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.POrders", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Models", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Expenditures", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Employees", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.DamageProducts", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Customers", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSales", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Companies", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Categorys", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.CashCollections", "ConcernID", "dbo.SisterConcerns", "ConcernID", cascadeDelete: true);
            //AddForeignKey("dbo.Products", "CategoryID", "dbo.Categorys", "CategoryID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSalesDetails", "CreditSalesID", "dbo.CreditSales", "CreditSalesID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSaleProducts", "CreditSalesID", "dbo.CreditSales", "CreditSalesID", cascadeDelete: true);
            //AddForeignKey("dbo.CreditSales", "CustomerID", "dbo.Customers", "CustomerID", cascadeDelete: true);
            //AddForeignKey("dbo.SOrders", "CustomerID", "dbo.Customers", "CustomerID", cascadeDelete: true);
            //AddForeignKey("dbo.CashCollections", "CustomerID", "dbo.Customers", "CustomerID");
        }
    }
}
